server {
    listen 80;

    # Onde os arquivos do Angular estão (dentro do container)
    root /usr/share/nginx/html;
    index index.html;

    location / {
        # Importante para as rotas do Angular (SPA) funcionarem no F5
        try_files $uri $uri/ /index.html;
    }

    # ISSO SUBSTITUI O SEU proxy.config.json
    location /api/ {
        # 'app-backend-loja' é o nome do serviço no seu docker-compose
        proxy_pass http://app-backend-loja:8081/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
